### ISSUE TITLE
Too many commands

### ISSUE THREAD

**Issue by thexperiments** [pimatic/pimatic-max#8]
It did heal after restarting the cube nevertheless I guess it would be a good idea to investigate why the que has filled up.

```
error [pimatic]: Error on evaluation of rule condition of rule deaktivierung-away-absenkung-wohnzimmer: Command was rejected: Too many commands send, the cube has no memory slots left.

**Comment by pimagical** [comment]
The Max Cube can't connect to the Max Cube Software (PC) and the Pimatic at
once.

So if you configured the Cube and Thermostats. You need to close the Max
Cube Software and restart the Cube.

So Pimatic can connect again to the Cube.

2017-12-15 10:16 GMT+01:00 thexperiments <notifications@github.com>:

**Comment by mwittig** [comment]
no response from @thexperiments 
closing this now

Will add troubleshooting hint following pimagical's comment
